collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.3996415
color:
  saturation: 0.8405017
  brandStrength: 1
  lightness: 0.8512544
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#E20A17'
    - '#0172C0'
    - '#32982B'
  rhythmicContrast: 0.1714456
layout_spectrum: 0.327957
name: Tracy
